Syslog                  true
Socket                  inet:8893@127.0.0.1
PidFile                 /run/opendmarc/opendmarc.pid
UserID                  opendmarc

AuthservID              mail.e-smail.ru
TrustedAuthservIDs      mail.e-smail.ru

SPFSelfValidate         true

RequiredHeaders         true

IgnoreAuthenticatedClients true

RejectFailures          true
