Syslog                  yes
SyslogSuccess           yes
LogWhy                  no
UMask                   007
UserID                  opendkim

Mode                    sv
Canonicalization        relaxed/simple

Domain                  e-smail.ru
Selector                mail
KeyFile                 /etc/opendkim/keys/e-smail.ru/mail.private

Socket                  inet:8891@127.0.0.1
PidFile                 /run/opendkim/opendkim.pid

OversignHeaders         From

InternalHosts           refile:/etc/opendkim/TrustedHosts
