import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR = path.resolve(__dirname, "../public/assets/svg");
const IDX_FILE_DIR = path.resolve(__dirname, "../src/assets/svg");
const INDEX_FILE = path.join(IDX_FILE_DIR, "index.ts");

// Converts file-name, file_name, or FileName to PascalCase
function toPascalCase(str) {
  return str
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase())
    .replace(/\s+/g, "");
}

async function generate() {
  try {
    const files = await fs.readdir(SVG_DIR);
    const svgFiles = files.filter((f) => f.endsWith(".svg")).sort();

    const exports = svgFiles.map((file) => {
      const baseName = path.basename(file, ".svg");
      let iconName = toPascalCase(baseName);

      // Ensures export name ends with "Icon" (e.g., Draft -> DraftIcon)
      if (!iconName.endsWith("Icon")) {
        iconName += "Icon";
      }

      return `export { default as ${iconName} } from "../../../public/assets/svg/${file}";`;
    });

    const fileContent = [
      "// Auto-generated by scripts/generate-icons.js. Do not edit manually.",
      ...exports,
      "",
    ].join("\n");

    await fs.writeFile(INDEX_FILE, fileContent, "utf-8");
    console.log(`Generated ${exports.length} icon exports in ${INDEX_FILE}`);
  } catch (error) {
    console.error("Failed to generate icon index:", error);
    process.exit(1);
  }
}

generate();
