// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/email/email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmailIdsByUserEmailIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmailIds  []int64                `protobuf:"varint,1,rep,packed,name=user_email_ids,json=userEmailIds,proto3" json:"user_email_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailIdsByUserEmailIdsRequest) Reset() {
	*x = GetEmailIdsByUserEmailIdsRequest{}
	mi := &file_proto_email_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailIdsByUserEmailIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailIdsByUserEmailIdsRequest) ProtoMessage() {}

func (x *GetEmailIdsByUserEmailIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailIdsByUserEmailIdsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailIdsByUserEmailIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmailIdsByUserEmailIdsRequest) GetUserEmailIds() []int64 {
	if x != nil {
		return x.UserEmailIds
	}
	return nil
}

type GetEmailIdsByUserEmailIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailIds      []int64                `protobuf:"varint,1,rep,packed,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailIdsByUserEmailIdsResponse) Reset() {
	*x = GetEmailIdsByUserEmailIdsResponse{}
	mi := &file_proto_email_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailIdsByUserEmailIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailIdsByUserEmailIdsResponse) ProtoMessage() {}

func (x *GetEmailIdsByUserEmailIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailIdsByUserEmailIdsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailIdsByUserEmailIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmailIdsByUserEmailIdsResponse) GetEmailIds() []int64 {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

type GetUserEmailIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailIDRequest) Reset() {
	*x = GetUserEmailIDRequest{}
	mi := &file_proto_email_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailIDRequest) ProtoMessage() {}

func (x *GetUserEmailIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserEmailIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserEmailIDRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *GetUserEmailIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserEmailIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmailId   int64                  `protobuf:"varint,1,opt,name=user_email_id,json=userEmailId,proto3" json:"user_email_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailIDResponse) Reset() {
	*x = GetUserEmailIDResponse{}
	mi := &file_proto_email_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailIDResponse) ProtoMessage() {}

func (x *GetUserEmailIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserEmailIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserEmailIDResponse) GetUserEmailId() int64 {
	if x != nil {
		return x.UserEmailId
	}
	return 0
}

type SwitchIsInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailId       int64                  `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchIsInboxRequest) Reset() {
	*x = SwitchIsInboxRequest{}
	mi := &file_proto_email_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchIsInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchIsInboxRequest) ProtoMessage() {}

func (x *SwitchIsInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchIsInboxRequest.ProtoReflect.Descriptor instead.
func (*SwitchIsInboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchIsInboxRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SwitchIsInboxRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

type SwitchIsInboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchIsInboxResponse) Reset() {
	*x = SwitchIsInboxResponse{}
	mi := &file_proto_email_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchIsInboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchIsInboxResponse) ProtoMessage() {}

func (x *SwitchIsInboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchIsInboxResponse.ProtoReflect.Descriptor instead.
func (*SwitchIsInboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchIsInboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      *int64                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3,oneof" json:"sender_id,omitempty"`
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAnonymous   bool                   `protobuf:"varint,6,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_email_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{6}
}

func (x *Email) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Email) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *Email) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Email) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

type GetEmailByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdRequest) Reset() {
	*x = GetEmailByIdRequest{}
	mi := &file_proto_email_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdRequest) ProtoMessage() {}

func (x *GetEmailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmailByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmailByIdRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *GetEmailByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdResponse) Reset() {
	*x = GetEmailByIdResponse{}
	mi := &file_proto_email_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdResponse) ProtoMessage() {}

func (x *GetEmailByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmailByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmailByIdResponse) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type CheckEmailAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessRequest) Reset() {
	*x = CheckEmailAccessRequest{}
	mi := &file_proto_email_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessRequest) ProtoMessage() {}

func (x *CheckEmailAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{9}
}

func (x *CheckEmailAccessRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *CheckEmailAccessRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckEmailAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessResponse) Reset() {
	*x = CheckEmailAccessResponse{}
	mi := &file_proto_email_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessResponse) ProtoMessage() {}

func (x *CheckEmailAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{10}
}

func (x *CheckEmailAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

type FolderEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderEmail   string                 `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail,proto3" json:"sender_email,omitempty"`
	SenderName    string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderSurname string                 `protobuf:"bytes,4,opt,name=sender_surname,json=senderSurname,proto3" json:"sender_surname,omitempty"`
	ReceiverList  []string               `protobuf:"bytes,5,rep,name=receiver_list,json=receiverList,proto3" json:"receiver_list,omitempty"`
	Header        string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsRead        bool                   `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	IsAnonymous   bool                   `protobuf:"varint,10,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderEmail) Reset() {
	*x = FolderEmail{}
	mi := &file_proto_email_email_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderEmail) ProtoMessage() {}

func (x *FolderEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderEmail.ProtoReflect.Descriptor instead.
func (*FolderEmail) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{11}
}

func (x *FolderEmail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FolderEmail) GetSenderEmail() string {
	if x != nil {
		return x.SenderEmail
	}
	return ""
}

func (x *FolderEmail) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *FolderEmail) GetSenderSurname() string {
	if x != nil {
		return x.SenderSurname
	}
	return ""
}

func (x *FolderEmail) GetReceiverList() []string {
	if x != nil {
		return x.ReceiverList
	}
	return nil
}

func (x *FolderEmail) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *FolderEmail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FolderEmail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FolderEmail) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *FolderEmail) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

type GetEmailsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailIds      []int64                `protobuf:"varint,1,rep,packed,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailsByIdsRequest) Reset() {
	*x = GetEmailsByIdsRequest{}
	mi := &file_proto_email_email_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailsByIdsRequest) ProtoMessage() {}

func (x *GetEmailsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{12}
}

func (x *GetEmailsByIdsRequest) GetEmailIds() []int64 {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

func (x *GetEmailsByIdsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*FolderEmail         `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailsByIdsResponse) Reset() {
	*x = GetEmailsByIdsResponse{}
	mi := &file_proto_email_email_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailsByIdsResponse) ProtoMessage() {}

func (x *GetEmailsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{13}
}

func (x *GetEmailsByIdsResponse) GetEmails() []*FolderEmail {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *GetEmailsByIdsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_proto_email_email_proto protoreflect.FileDescriptor

const file_proto_email_email_proto_rawDesc = "" +
	"\x0a\x17\x70\x72\x6f\x74\x6f\x2f\x65\x6d\x61\x69\x6c\x2f\x65\x6d\x61\x69\x6c\x2e\x70\x72\x6f\x74\x6f\x12\x05\x65\x6d\x61\x69\x6c\x1a\x1f\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x2e" +
	"\x70\x72\x6f\x74\x6f\x22\x48\x0a\x20\x47\x65\x74\x45\x6d\x61\x69\x6c\x49\x64\x73\x42\x79\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x52\x65\x71\x75\x65\x73\x74\x12\x24\x0a\x0e\x75\x73\x65\x72\x5f\x65\x6d\x61\x69\x6c\x5f\x69\x64\x73\x18" +
	"\x01\x20\x03\x28\x03\x52\x0c\x75\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x22\x40\x0a\x21\x47\x65\x74\x45\x6d\x61\x69\x6c\x49\x64\x73\x42\x79\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x1b\x0a\x09" +
	"\x65\x6d\x61\x69\x6c\x5f\x69\x64\x73\x18\x01\x20\x03\x28\x03\x52\x08\x65\x6d\x61\x69\x6c\x49\x64\x73\x22\x4b\x0a\x15\x47\x65\x74\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x44\x52\x65\x71\x75\x65\x73\x74\x12\x19\x0a\x08\x65\x6d\x61\x69\x6c\x5f" +
	"\x69\x64\x18\x01\x20\x01\x28\x03\x52\x07\x65\x6d\x61\x69\x6c\x49\x64\x12\x17\x0a\x07\x75\x73\x65\x72\x5f\x69\x64\x18\x02\x20\x01\x28\x03\x52\x06\x75\x73\x65\x72\x49\x64\x22\x3c\x0a\x16\x47\x65\x74\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x44" +
	"\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x22\x0a\x0d\x75\x73\x65\x72\x5f\x65\x6d\x61\x69\x6c\x5f\x69\x64\x18\x01\x20\x01\x28\x03\x52\x0b\x75\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x22\x4a\x0a\x14\x53\x77\x69\x74\x63\x68\x49\x73\x49\x6e\x62\x6f" +
	"\x78\x52\x65\x71\x75\x65\x73\x74\x12\x17\x0a\x07\x75\x73\x65\x72\x5f\x69\x64\x18\x01\x20\x01\x28\x03\x52\x06\x75\x73\x65\x72\x49\x64\x12\x19\x0a\x08\x65\x6d\x61\x69\x6c\x5f\x69\x64\x18\x02\x20\x01\x28\x03\x52\x07\x65\x6d\x61\x69\x6c\x49\x64" +
	"\x22\x31\x0a\x15\x53\x77\x69\x74\x63\x68\x49\x73\x49\x6e\x62\x6f\x78\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x18\x0a\x07\x73\x75\x63\x63\x65\x73\x73\x18\x01\x20\x01\x28\x08\x52\x07\x73\x75\x63\x63\x65\x73\x73\x22\xb5\x01\x0a\x05\x45\x6d\x61\x69" +
	"\x6c\x12\x0e\x0a\x02\x69\x64\x18\x01\x20\x01\x28\x03\x52\x02\x69\x64\x12\x20\x0a\x09\x73\x65\x6e\x64\x65\x72\x5f\x69\x64\x18\x02\x20\x01\x28\x03\x48\x00\x52\x08\x73\x65\x6e\x64\x65\x72\x49\x64\x88\x01\x01\x12\x16\x0a\x06\x68\x65\x61\x64\x65" +
	"\x72\x18\x03\x20\x01\x28\x09\x52\x06\x68\x65\x61\x64\x65\x72\x12\x12\x0a\x04\x62\x6f\x64\x79\x18\x04\x20\x01\x28\x09\x52\x04\x62\x6f\x64\x79\x12\x1d\x0a\x0a\x63\x72\x65\x61\x74\x65\x64\x5f\x61\x74\x18\x05\x20\x01\x28\x09\x52\x09\x63\x72\x65" +
	"\x61\x74\x65\x64\x41\x74\x12\x21\x0a\x0c\x69\x73\x5f\x61\x6e\x6f\x6e\x79\x6d\x6f\x75\x73\x18\x06\x20\x01\x28\x08\x52\x0b\x69\x73\x41\x6e\x6f\x6e\x79\x6d\x6f\x75\x73\x42\x0c\x0a\x0a\x5f\x73\x65\x6e\x64\x65\x72\x5f\x69\x64\x22\x49\x0a\x13\x47" +
	"\x65\x74\x45\x6d\x61\x69\x6c\x42\x79\x49\x64\x52\x65\x71\x75\x65\x73\x74\x12\x19\x0a\x08\x65\x6d\x61\x69\x6c\x5f\x69\x64\x18\x01\x20\x01\x28\x03\x52\x07\x65\x6d\x61\x69\x6c\x49\x64\x12\x17\x0a\x07\x75\x73\x65\x72\x5f\x69\x64\x18\x02\x20\x01" +
	"\x28\x03\x52\x06\x75\x73\x65\x72\x49\x64\x22\x3a\x0a\x14\x47\x65\x74\x45\x6d\x61\x69\x6c\x42\x79\x49\x64\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x22\x0a\x05\x65\x6d\x61\x69\x6c\x18\x01\x20\x01\x28\x0b\x32\x0c\x2e\x65\x6d\x61\x69\x6c\x2e\x45\x6d" +
	"\x61\x69\x6c\x52\x05\x65\x6d\x61\x69\x6c\x22\x4d\x0a\x17\x43\x68\x65\x63\x6b\x45\x6d\x61\x69\x6c\x41\x63\x63\x65\x73\x73\x52\x65\x71\x75\x65\x73\x74\x12\x19\x0a\x08\x65\x6d\x61\x69\x6c\x5f\x69\x64\x18\x01\x20\x01\x28\x03\x52\x07\x65\x6d\x61" +
	"\x69\x6c\x49\x64\x12\x17\x0a\x07\x75\x73\x65\x72\x5f\x69\x64\x18\x02\x20\x01\x28\x03\x52\x06\x75\x73\x65\x72\x49\x64\x22\x39\x0a\x18\x43\x68\x65\x63\x6b\x45\x6d\x61\x69\x6c\x41\x63\x63\x65\x73\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x1d\x0a" +
	"\x0a\x68\x61\x73\x5f\x61\x63\x63\x65\x73\x73\x18\x01\x20\x01\x28\x08\x52\x09\x68\x61\x73\x41\x63\x63\x65\x73\x73\x22\xd0\x02\x0a\x0b\x46\x6f\x6c\x64\x65\x72\x45\x6d\x61\x69\x6c\x12\x0e\x0a\x02\x69\x64\x18\x01\x20\x01\x28\x03\x52\x02\x69\x64" +
	"\x12\x21\x0a\x0c\x73\x65\x6e\x64\x65\x72\x5f\x65\x6d\x61\x69\x6c\x18\x02\x20\x01\x28\x09\x52\x0b\x73\x65\x6e\x64\x65\x72\x45\x6d\x61\x69\x6c\x12\x1f\x0a\x0b\x73\x65\x6e\x64\x65\x72\x5f\x6e\x61\x6d\x65\x18\x03\x20\x01\x28\x09\x52\x0a\x73\x65" +
	"\x6e\x64\x65\x72\x4e\x61\x6d\x65\x12\x25\x0a\x0e\x73\x65\x6e\x64\x65\x72\x5f\x73\x75\x72\x6e\x61\x6d\x65\x18\x04\x20\x01\x28\x09\x52\x0d\x73\x65\x6e\x64\x65\x72\x53\x75\x72\x6e\x61\x6d\x65\x12\x23\x0a\x0d\x72\x65\x63\x65\x69\x76\x65\x72\x5f" +
	"\x6c\x69\x73\x74\x18\x05\x20\x03\x28\x09\x52\x0c\x72\x65\x63\x65\x69\x76\x65\x72\x4c\x69\x73\x74\x12\x16\x0a\x06\x68\x65\x61\x64\x65\x72\x18\x06\x20\x01\x28\x09\x52\x06\x68\x65\x61\x64\x65\x72\x12\x12\x0a\x04\x62\x6f\x64\x79\x18\x07\x20\x01" +
	"\x28\x09\x52\x04\x62\x6f\x64\x79\x12\x39\x0a\x0a\x63\x72\x65\x61\x74\x65\x64\x5f\x61\x74\x18\x08\x20\x01\x28\x0b\x32\x1a\x2e\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x52\x09\x63\x72" +
	"\x65\x61\x74\x65\x64\x41\x74\x12\x17\x0a\x07\x69\x73\x5f\x72\x65\x61\x64\x18\x09\x20\x01\x28\x08\x52\x06\x69\x73\x52\x65\x61\x64\x12\x21\x0a\x0c\x69\x73\x5f\x61\x6e\x6f\x6e\x79\x6d\x6f\x75\x73\x18\x0a\x20\x01\x28\x08\x52\x0b\x69\x73\x41\x6e" +
	"\x6f\x6e\x79\x6d\x6f\x75\x73\x22\x4d\x0a\x15\x47\x65\x74\x45\x6d\x61\x69\x6c\x73\x42\x79\x49\x64\x73\x52\x65\x71\x75\x65\x73\x74\x12\x1b\x0a\x09\x65\x6d\x61\x69\x6c\x5f\x69\x64\x73\x18\x01\x20\x03\x28\x03\x52\x08\x65\x6d\x61\x69\x6c\x49\x64" +
	"\x73\x12\x17\x0a\x07\x75\x73\x65\x72\x5f\x69\x64\x18\x02\x20\x01\x28\x03\x52\x06\x75\x73\x65\x72\x49\x64\x22\x67\x0a\x16\x47\x65\x74\x45\x6d\x61\x69\x6c\x73\x42\x79\x49\x64\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x2a\x0a\x06\x65\x6d\x61\x69" +
	"\x6c\x73\x18\x01\x20\x03\x28\x0b\x32\x12\x2e\x65\x6d\x61\x69\x6c\x2e\x46\x6f\x6c\x64\x65\x72\x45\x6d\x61\x69\x6c\x52\x06\x65\x6d\x61\x69\x6c\x73\x12\x21\x0a\x0c\x75\x6e\x72\x65\x61\x64\x5f\x63\x6f\x75\x6e\x74\x18\x02\x20\x01\x28\x05\x52\x0b" +
	"\x75\x6e\x72\x65\x61\x64\x43\x6f\x75\x6e\x74\x32\x86\x04\x0a\x0c\x45\x6d\x61\x69\x6c\x53\x65\x72\x76\x69\x63\x65\x12\x47\x0a\x0c\x47\x65\x74\x45\x6d\x61\x69\x6c\x42\x79\x49\x64\x12\x1a\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x45\x6d\x61\x69" +
	"\x6c\x42\x79\x49\x64\x52\x65\x71\x75\x65\x73\x74\x1a\x1b\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x45\x6d\x61\x69\x6c\x42\x79\x49\x64\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x6e\x0a\x19\x47\x65\x74\x45\x6d\x61\x69\x6c\x49\x64\x73\x42\x79\x55\x73" +
	"\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x12\x27\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x45\x6d\x61\x69\x6c\x49\x64\x73\x42\x79\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x52\x65\x71\x75\x65\x73\x74\x1a\x28\x2e\x65\x6d\x61\x69\x6c\x2e" +
	"\x47\x65\x74\x45\x6d\x61\x69\x6c\x49\x64\x73\x42\x79\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x64\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x53\x0a\x10\x43\x68\x65\x63\x6b\x45\x6d\x61\x69\x6c\x41\x63\x63\x65\x73\x73\x12\x1e\x2e\x65\x6d\x61\x69" +
	"\x6c\x2e\x43\x68\x65\x63\x6b\x45\x6d\x61\x69\x6c\x41\x63\x63\x65\x73\x73\x52\x65\x71\x75\x65\x73\x74\x1a\x1f\x2e\x65\x6d\x61\x69\x6c\x2e\x43\x68\x65\x63\x6b\x45\x6d\x61\x69\x6c\x41\x63\x63\x65\x73\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x4d" +
	"\x0a\x0e\x47\x65\x74\x45\x6d\x61\x69\x6c\x73\x42\x79\x49\x64\x73\x12\x1c\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x45\x6d\x61\x69\x6c\x73\x42\x79\x49\x64\x73\x52\x65\x71\x75\x65\x73\x74\x1a\x1d\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x45\x6d" +
	"\x61\x69\x6c\x73\x42\x79\x49\x64\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x4a\x0a\x0d\x53\x77\x69\x74\x63\x68\x49\x73\x49\x6e\x62\x6f\x78\x12\x1b\x2e\x65\x6d\x61\x69\x6c\x2e\x53\x77\x69\x74\x63\x68\x49\x73\x49\x6e\x62\x6f\x78\x52\x65\x71\x75" +
	"\x65\x73\x74\x1a\x1c\x2e\x65\x6d\x61\x69\x6c\x2e\x53\x77\x69\x74\x63\x68\x49\x73\x49\x6e\x62\x6f\x78\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x4d\x0a\x0e\x47\x65\x74\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x44\x12\x1c\x2e\x65\x6d\x61\x69\x6c\x2e" +
	"\x47\x65\x74\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x44\x52\x65\x71\x75\x65\x73\x74\x1a\x1d\x2e\x65\x6d\x61\x69\x6c\x2e\x47\x65\x74\x55\x73\x65\x72\x45\x6d\x61\x69\x6c\x49\x44\x52\x65\x73\x70\x6f\x6e\x73\x65\x42\x0f\x5a\x0d\x2e\x2f\x70\x72" +
	"\x6f\x74\x6f\x2f\x65\x6d\x61\x69\x6c\x62\x06\x70\x72\x6f\x74\x6f\x33"

var (
	file_proto_email_email_proto_rawDescOnce sync.Once
	file_proto_email_email_proto_rawDescData []byte
)

func file_proto_email_email_proto_rawDescGZIP() []byte {
	file_proto_email_email_proto_rawDescOnce.Do(func() {
		file_proto_email_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)))
	})
	return file_proto_email_email_proto_rawDescData
}

var file_proto_email_email_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_email_email_proto_goTypes = []any{
	(*GetEmailIdsByUserEmailIdsRequest)(nil),  // 0: email.GetEmailIdsByUserEmailIdsRequest
	(*GetEmailIdsByUserEmailIdsResponse)(nil), // 1: email.GetEmailIdsByUserEmailIdsResponse
	(*GetUserEmailIDRequest)(nil),             // 2: email.GetUserEmailIDRequest
	(*GetUserEmailIDResponse)(nil),            // 3: email.GetUserEmailIDResponse
	(*SwitchIsInboxRequest)(nil),              // 4: email.SwitchIsInboxRequest
	(*SwitchIsInboxResponse)(nil),             // 5: email.SwitchIsInboxResponse
	(*Email)(nil),                             // 6: email.Email
	(*GetEmailByIdRequest)(nil),               // 7: email.GetEmailByIdRequest
	(*GetEmailByIdResponse)(nil),              // 8: email.GetEmailByIdResponse
	(*CheckEmailAccessRequest)(nil),           // 9: email.CheckEmailAccessRequest
	(*CheckEmailAccessResponse)(nil),          // 10: email.CheckEmailAccessResponse
	(*FolderEmail)(nil),                       // 11: email.FolderEmail
	(*GetEmailsByIdsRequest)(nil),             // 12: email.GetEmailsByIdsRequest
	(*GetEmailsByIdsResponse)(nil),            // 13: email.GetEmailsByIdsResponse
	(*timestamppb.Timestamp)(nil),             // 14: google.protobuf.Timestamp
}
var file_proto_email_email_proto_depIdxs = []int32{
	6,  // 0: email.GetEmailByIdResponse.email:type_name -> email.Email
	14, // 1: email.FolderEmail.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: email.GetEmailsByIdsResponse.emails:type_name -> email.FolderEmail
	7,  // 3: email.EmailService.GetEmailById:input_type -> email.GetEmailByIdRequest
	0,  // 4: email.EmailService.GetEmailIdsByUserEmailIds:input_type -> email.GetEmailIdsByUserEmailIdsRequest
	9,  // 5: email.EmailService.CheckEmailAccess:input_type -> email.CheckEmailAccessRequest
	12, // 6: email.EmailService.GetEmailsByIds:input_type -> email.GetEmailsByIdsRequest
	4,  // 7: email.EmailService.SwitchIsInbox:input_type -> email.SwitchIsInboxRequest
	2,  // 8: email.EmailService.GetUserEmailID:input_type -> email.GetUserEmailIDRequest
	8,  // 9: email.EmailService.GetEmailById:output_type -> email.GetEmailByIdResponse
	1,  // 10: email.EmailService.GetEmailIdsByUserEmailIds:output_type -> email.GetEmailIdsByUserEmailIdsResponse
	10, // 11: email.EmailService.CheckEmailAccess:output_type -> email.CheckEmailAccessResponse
	13, // 12: email.EmailService.GetEmailsByIds:output_type -> email.GetEmailsByIdsResponse
	5,  // 13: email.EmailService.SwitchIsInbox:output_type -> email.SwitchIsInboxResponse
	3,  // 14: email.EmailService.GetUserEmailID:output_type -> email.GetUserEmailIDResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_email_email_proto_init() }
func file_proto_email_email_proto_init() {
	if File_proto_email_email_proto != nil {
		return
	}
	file_proto_email_email_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_email_proto_goTypes,
		DependencyIndexes: file_proto_email_email_proto_depIdxs,
		MessageInfos:      file_proto_email_email_proto_msgTypes,
	}.Build()
	File_proto_email_email_proto = out.File
	file_proto_email_email_proto_goTypes = nil
	file_proto_email_email_proto_depIdxs = nil
}
